- name: Cache the .tox dir
  uses: actions/cache@v2
  with:
    path: .tox
    key: ${{ runner.os }}-tox-${{ hashFiles('tox.ini', 'requirements*', 'setup.py', 'setup.cfg') }}
    restore-keys: |
      ${{ runner.os }}-tox-