version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: celery
    versions:
    - ">= 5.0.a"
    - "< 5.1"

- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
  ignore:
    # Allow only patch updates for docker images automatically
    - update-types: ["version-update:semver-major", "version-update:semver-minor"]
