[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"

[tool.hdev.template.import_comment]
".github/workflows/template/continuous-integration.yml" = ".github/workflows/continuous-integration.yml"