name: CI
on:
  push:
  workflow_dispatch:
  workflow_call:
jobs:
  Format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: Cache the .tox dir
        uses: actions/cache@v3
        with:
          path: .tox
          key: format-${{ runner.os }}-tox-${{ hashFiles('tox.ini') }}-${{ hashFiles('requirements/*') }}
          restore-keys: |
            format-${{ runner.os }}-tox-
      - run: python -m pip install 'tox<4'
      - run: tox -e checkformatting
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: Cache the .tox dir
        uses: actions/cache@v3
        with:
          path: .tox
          key: lint-${{ runner.os }}-tox-${{ hashFiles('tox.ini') }}-${{ hashFiles('requirements/*') }}
          restore-keys: |
            lint-${{ runner.os }}-tox-
      - run: python -m pip install 'tox<4'
      - run: tox -e lint
  Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: Cache the .tox dir
        uses: actions/cache@v3
        with:
          path: .tox
          key: tests-${{ runner.os }}-tox-${{ hashFiles('tox.ini') }}-${{ hashFiles('requirements/*') }}
          restore-keys: |
            tests-${{ runner.os }}-tox-
      - run: python -m pip install 'tox<4'
      - run: tox -e tests
      - name: Upload coverage file
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: .coverage.*
  Coverage:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: Cache the .tox dir
        uses: actions/cache@v3
        with:
          path: .tox
          key: coverage-${{ runner.os }}-tox-${{ hashFiles('tox.ini') }}-${{ hashFiles('requirements/*') }}
          restore-keys: |
            coverage-${{ runner.os }}-tox-
      - name: Download coverage files
        uses: actions/download-artifact@v3
        with:
          name: coverage
      - run: python -m pip install 'tox<4'
      - run: tox -e coverage
  Functests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: Cache the .tox dir
        uses: actions/cache@v3
        with:
          path: .tox
          key: functests-${{ runner.os }}-tox-${{ hashFiles('tox.ini') }}-${{ hashFiles('requirements/*') }}
          restore-keys: |
            functests-${{ runner.os }}-tox-
      - run: python -m pip install 'tox<4'
      - run: tox -e functests
