name: Deploy

concurrency:
  group: ${{ github.event.repository.name }}-deploy
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  continuous-integration:
    uses: ./.github/workflows/continuous-integration.yml
    name: continuous integration

  create-image:
    needs: continuous-integration
    uses: hypothesis/workflows/.github/workflows/dockerhub.yml@main
    with:
      Application: ${{ github.event.repository.name }}
    secrets: inherit

  QA:
    needs: create-image
    uses: hypothesis/workflows/.github/workflows/deploy.yml@main
    with:
      operation: deploy
      github_environment_name: QA
      aws_region: us-west-1
      elasticbeanstalk_application: h-periodic
      elasticbeanstalk_environment: qa
      docker_tag: ${{ needs.create-image.outputs.docker_tag }}
    secrets: inherit

  Production:
    needs: [create-image, QA]
    uses: hypothesis/workflows/.github/workflows/deploy.yml@main
    with:
      operation: deploy
      github_environment_name: Production
      aws_region: us-west-1
      elasticbeanstalk_application: h-periodic
      elasticbeanstalk_environment: prod
      docker_tag: ${{ needs.create-image.outputs.docker_tag }}
    secrets: inherit

  Production_Canada:
    needs: [create-image, QA]
    name: Production (Canada)
    uses: hypothesis/workflows/.github/workflows/deploy.yml@main
    with:
      operation: deploy
      github_environment_name: Production (Canada)
      aws_region: ca-central-1
      elasticbeanstalk_application: h-periodic
      elasticbeanstalk_environment: prod
      docker_tag: ${{ needs.create-image.outputs.docker_tag }}
    secrets: inherit
